name: CD
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      GEM_HOST_API_KEY: "${{secrets.RUBYGEM_API}}"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
    - name: Setup to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
    - name: Install dependencies
      run: |
        gem update --system 3.5.11
        bundle install
    - name: Release
      run: |
        TAG=$(bundle exec rake version | tr -d '"')
        git tag $TAG
        git push --tags
        gh release create $TAG --generate-notes
        bundle exec rake build
        gem push pkg/*
    