# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CD

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
      with:
        ruby-version: 2.6
    - name: Setup API key
      run: |
        mkdir -p ~/.local/share/gem/
        echo "${{ secrets.RUBYGEM_API }}" | base64 -d > ~/.local/share/gem/credentials
    - name: Release
      run: |
        TAG=$(rake version | tr -d '"')
        bundle install
        git tag $TAG
        git push --tags
        gh release create $TAG --generate-notes
        rake build
        gem push pkg/*