# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
      with:
        ruby-version: 2.6
    - name: Install Docker
      run: curl https://get.docker.com | sh
    - name: Setup docker
      run: |
        bin/setup 
        sudo bin/setup
    - name: Run tests
      run: rspec
    
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SVU
      run: echo 'deb [trusted=yes] https://apt.fury.io/caarlos0/ /' | tee /etc/apt/sources.list.d/caarlos0.list && apt update -y && apt install svu -y
    - name: Check version
      run: |
        [ $(svu n) != $(rake version | tr -d '"') ] && echo "Need to update version.rb file. Exiting... ";exit 1