# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
      with:
        ruby-version: 2.6
    - name: Install Docker
      run: curl https://get.docker.com | sh
    - name: Install dependencies
      run: |
        bin/setup 
        sudo bin/setup
    - name: Test misc
      run: rspec spec/misc/*.rb
    - name: Test Image
      run: rspec spec/endpoints/image_spec.rb:1
    - name: Test Image authentication
      run: rspec spec/endpoints/image_spec.rb:194
      continue-on-error: true
    - name: Test Container
      run: rspec spec/endpoints/container_spec.rb
    - name: Test Volume
      run: rspec spec/endpoints/volume_spec.rb
    - name: Test Network
      run: rspec spec/endpoints/network_spec.rb
    - name: Test System
      run: rspec spec/endpoints/system_spec.rb
    - name: Test Exec
      run: rspec spec/endpoints/exec_spec.rb
    - name: Test Swarm
      run: rspec spec/endpoints/swarm_spec.rb
    - name: Test Node
      run: rspec spec/endpoints/node_spec.rb
    - name: Test Service
      run: rspec spec/endpoints/service_spec.rb
    - name: Test Task
      run: rspec spec/endpoints/task_spec.rb
    - name: Test Secret
      run: rspec spec/endpoints/secret_spec.rb
    - name: Test Config
      run: rspec spec/endpoints/config_spec.rb
    - name: Test Plugin
      run: rspec spec/endpoints/plugin_spec.rb
  